name: Discord Notification

on:
  push: 
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: tsickert/discord-webhook@v5
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            🚀 `${{ github.repository }}`
            ✅ `${{ github.actor }}` pushed to **${{ github.ref_name }}**
            💬 `${{ github.event.head_commit.message }}`
            🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}
