name: Discord Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 `${{ github.repository }}`
            ✅ `${{ github.actor }}` pushed to **${{ github.ref_name }}**
            💬 `${{ github.event.head_commit.message }}`
            🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}
