name: Discord Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_MESSAGE: |
            🚀 Repo: ${{ github.repository }}
            🧑 Author: ${{ github.actor }}
            🔀 Branch: ${{ github.ref_name }}
            💬 Commit: ${{ github.event.head_commit.message }}
